---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dummy-ds
  labels:
    k8s-app: dummy-ds
    version: v1
spec:
  selector:
    matchLabels:
      k8s-app: dummy-ds
  template:
    metadata:
      labels:
        k8s-app: dummy-ds
        version: v1
    spec:
      containers:
        - name: dummy-ds
          image: ubuntu:latest
          command: ["sleep"]
          args: ["infinity"]
          volumeMounts:
            - mountPath: /data-mount
              name: dd-csi-volume
      volumes:
        - name: dd-csi-volume
          csi:
            driver: example.csi.driver
            readOnly: false
