kind: Pod
apiVersion: v1
metadata:
  name: test-csi-pod
spec:
  containers:
    - name: container
      image: nginx
      volumeMounts:
        - mountPath: /data-mount
          name: dd-csi-volume
  volumes:
    - name: dd-csi-volume
      csi:
        driver: example.csi.driver
        readOnly: false
