apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  storageClassName: my-csi-storageclass
  volumeName: example-pv
